package com.bokchoy.nowcode_community.mapper;

import com.bokchoy.nowcode_community.entity.DiscussPost;
import com.bokchoy.nowcode_community.entity.DiscussPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DiscussPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    long countByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    int deleteByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    int insert(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    int insertSelective(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    List<DiscussPost> selectByExampleWithBLOBsWithRowbounds(DiscussPostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    List<DiscussPost> selectByExampleWithBLOBs(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    List<DiscussPost> selectByExampleWithRowbounds(DiscussPostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    List<DiscussPost> selectByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    DiscussPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    int updateByExampleSelective(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    int updateByExample(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    int updateByPrimaryKeySelective(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    int updateByPrimaryKey(DiscussPost record);
}