package com.bokchoy.nowcode_community.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table discuss_post
 */
public class DiscussPost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.user_id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.title
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private String title;

    /**
     * Database Column Remarks:
     *   0-普通; 1-置顶;
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.type
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   0-正常; 1-精华; 2-拉黑;
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.status
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.create_time
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.comment_count
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.score
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.content
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.id
     *
     * @return the value of discuss_post.id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.id
     *
     * @param id the value for discuss_post.id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.user_id
     *
     * @return the value of discuss_post.user_id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.user_id
     *
     * @param userId the value for discuss_post.user_id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.title
     *
     * @return the value of discuss_post.title
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.title
     *
     * @param title the value for discuss_post.title
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.type
     *
     * @return the value of discuss_post.type
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.type
     *
     * @param type the value for discuss_post.type
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.status
     *
     * @return the value of discuss_post.status
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.status
     *
     * @param status the value for discuss_post.status
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.create_time
     *
     * @return the value of discuss_post.create_time
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.create_time
     *
     * @param createTime the value for discuss_post.create_time
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.comment_count
     *
     * @return the value of discuss_post.comment_count
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.comment_count
     *
     * @param commentCount the value for discuss_post.comment_count
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.score
     *
     * @return the value of discuss_post.score
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.score
     *
     * @param score the value for discuss_post.score
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.content
     *
     * @return the value of discuss_post.content
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.content
     *
     * @param content the value for discuss_post.content
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", title=").append(title);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", commentCount=").append(commentCount);
        sb.append(", score=").append(score);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}