package com.bokchoy.nowcode_community.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table login_ticket
 */
public class LoginTicket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_ticket.id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_ticket.user_id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_ticket.ticket
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private String ticket;

    /**
     * Database Column Remarks:
     *   0-有效; 1-无效;
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_ticket.status
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_ticket.expired
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    private Date expired;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_ticket.id
     *
     * @return the value of login_ticket.id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_ticket.id
     *
     * @param id the value for login_ticket.id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_ticket.user_id
     *
     * @return the value of login_ticket.user_id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_ticket.user_id
     *
     * @param userId the value for login_ticket.user_id
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_ticket.ticket
     *
     * @return the value of login_ticket.ticket
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_ticket.ticket
     *
     * @param ticket the value for login_ticket.ticket
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setTicket(String ticket) {
        this.ticket = ticket == null ? null : ticket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_ticket.status
     *
     * @return the value of login_ticket.status
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_ticket.status
     *
     * @param status the value for login_ticket.status
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_ticket.expired
     *
     * @return the value of login_ticket.expired
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public Date getExpired() {
        return expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_ticket.expired
     *
     * @param expired the value for login_ticket.expired
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    public void setExpired(Date expired) {
        this.expired = expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Oct 18 15:26:07 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", ticket=").append(ticket);
        sb.append(", status=").append(status);
        sb.append(", expired=").append(expired);
        sb.append("]");
        return sb.toString();
    }
}