package com.bokchoy.nowcode_community.entity;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.from_id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    private Integer fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.to_id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    private Integer toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.conversation_id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    private String conversationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.status
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.from_id
     *
     * @return the value of message.from_id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.from_id
     *
     * @param fromId the value for message.from_id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.to_id
     *
     * @return the value of message.to_id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.to_id
     *
     * @param toId the value for message.to_id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.conversation_id
     *
     * @return the value of message.conversation_id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public String getConversationId() {
        return conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.conversation_id
     *
     * @param conversationId the value for message.conversation_id
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public void setConversationId(String conversationId) {
        this.conversationId = conversationId == null ? null : conversationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Sun Oct 17 16:02:39 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}